{% set name = "miss-hit-core" %}
{% set version = "0.9.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/miss_hit_core-{{ version }}.tar.gz
  sha256: 5b2dd8e0c1c27f5024d3130aabfbcc50f9e29e5bec9e32f071882e28b65d6208

build:
  entry_points:
    - mh_style = miss_hit_core.mh_style:main
    - mh_metric = miss_hit_core.mh_metric:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0

test:
  imports:
    - miss_hit_core
  commands:
    - pip check
    - mh_style --help
    - mh_metric --help
  requires:
    - pip

about:
  home: https://misshit.org
  summary: Code formatting and code metrics for programs written in the MATLAB/Simulink and Octave languages.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
